# Generated by Django 2.0.3 on 2018-03-06 21:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('race', models.CharField(max_length=12)),
                ('aura', models.CharField(max_length=64)),
                ('sembelence', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=10)),
                ('fanuas_type', models.CharField(max_length=32)),
                ('citizenship', models.CharField(max_length=32)),
                ('occupation', models.CharField(max_length=32)),
                ('background', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(on_delete='CASCADE', related_name='player', to='remnant_character.User'),
        ),
    ]
