# Generated by Django 2.0.3 on 2018-03-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=128)),
                ('weapon_type', models.CharField(max_length=64)),
                ('wield_type', models.CharField(max_length=7)),
                ('attack_speed', models.CharField(max_length=16)),
                ('hit_bonus', models.PositiveSmallIntegerField()),
                ('damage_class', models.CharField(max_length=32)),
                ('damage_bonus', models.SmallIntegerField()),
                ('weapon_range', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_name', to='remnant_character.User')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='remnant_character.User'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='wielder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PC', to='remnant_character.Character'),
        ),
    ]
