# Generated by Django 2.0.3 on 2018-03-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0002_auto_20180306_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='player',
        ),
    ]
