# Generated by Django 2.0.3 on 2018-03-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0003_remove_weapon_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strength', models.PositiveSmallIntegerField()),
                ('Dexterity', models.PositiveSmallIntegerField()),
                ('Constitution', models.PositiveSmallIntegerField()),
                ('Charisma', models.PositiveSmallIntegerField()),
                ('Intelligence', models.PositiveSmallIntegerField()),
                ('Wisdom', models.PositiveSmallIntegerField()),
                ('character_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='remnant_character.Character')),
            ],
        ),
    ]
