# Generated by Django 2.0.3 on 2018-03-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0004_primarystatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Charisma',
        ),
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Constitution',
        ),
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Dexterity',
        ),
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Intelligence',
        ),
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Strength',
        ),
        migrations.RemoveField(
            model_name='primarystatistics',
            name='Wisdom',
        ),
    ]
