# Generated by Django 2.0.3 on 2018-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0005_auto_20180306_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarystatistics',
            name='armor_rating',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='constitution',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='hit_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='player_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='strength',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='primarystatistics',
            name='wisdom',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
