# Generated by Django 2.0.3 on 2018-03-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0006_auto_20180306_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustPouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.PositiveSmallIntegerField(default=0)),
                ('fire', models.PositiveSmallIntegerField(default=0)),
                ('lightning', models.PositiveSmallIntegerField(default=0)),
                ('water', models.PositiveSmallIntegerField(default=0)),
                ('character_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_dust', to='remnant_character.Character')),
            ],
        ),
    ]
