# Generated by Django 2.0.3 on 2018-03-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remnant_character', '0007_dustpouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics', models.PositiveSmallIntegerField(default=0)),
                ('animal_handling', models.PositiveSmallIntegerField(default=0)),
                ('dust', models.PositiveSmallIntegerField(default=0)),
                ('athletics', models.PositiveSmallIntegerField(default=0)),
                ('deception', models.PositiveSmallIntegerField(default=0)),
                ('history', models.PositiveSmallIntegerField(default=0)),
                ('insight', models.PositiveSmallIntegerField(default=0)),
                ('intimidation', models.PositiveSmallIntegerField(default=0)),
                ('investigation', models.PositiveSmallIntegerField(default=0)),
                ('medicine', models.PositiveSmallIntegerField(default=0)),
                ('nature', models.PositiveSmallIntegerField(default=0)),
                ('perception', models.PositiveSmallIntegerField(default=0)),
                ('performance', models.PositiveSmallIntegerField(default=0)),
                ('grimm', models.PositiveSmallIntegerField(default=0)),
                ('sleight_of_hand', models.PositiveSmallIntegerField(default=0)),
                ('stealth', models.PositiveSmallIntegerField(default=0)),
                ('survival', models.PositiveSmallIntegerField(default=0)),
                ('character_skilled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_skills', to='remnant_character.Character')),
            ],
        ),
    ]
